### ISSUE TITLE
I'm not understand the experiment on the unseen types of Otyper

### ISSUE THREAD

**Issue by herbertchen1** [CogComp/zoe#22]
1.the prediction of Otyper on unseen type is a concatenation of the evaluation part of each folds?? To get the score on Table 4, I need to compare the concatenation with the whole ground truth in Figer?

**Comment by Slash0BZ** [comment]
Hi, I am not entirely sure what you mean, but assuming you are asking how the unseen types experiment is done on OTyper, it’s splitting into N_types folds, each fold is trained on N_types - 1 types, and test on the left out single type.

I am not sure what you mean by concatenation, the specific metric calculation is in the paper, after you get the pet type results.

Please let me know if this answers your question, thank you.

**Comment by herbertchen1** [comment]
So the evaluation on the left-out single type is done as a binary classification? (in other world, without trying to figure out whether it's a seen type instance)
BTW, it's a very giant but delicate work!!

**Comment by herbertchen1** [comment]
> Hi, I am not entirely sure what you mean, but assuming you are asking how the unseen types experiment is done on OTyper, it’s splitted into N_types folds, each fold is trained on N_types - 1 types, and test on the left out single type.
> 
> I am not sure what you mean by concatenation, the specific metric calculation is in the paper, after you get the pet type results.
> 
> Please let me know if this answers your question, thank you.
So the evaluation on the left-out single type is done as a binary classification? (in other word, without trying to figure out whether the mention is a seen type instance)
BTW, it's a very giant but delicate work!!

**Comment by Slash0BZ** [comment]
Yes that’s correct. Thanks for your interest!
