### ISSUE TITLE
Question about ELMo embedding caching design

### ISSUE THREAD

**Issue by hitercs** [CogComp/zoe#23]
Hi,

I have a question about your ELMo embedding caching design. When querying caching ELMo vectors of standard dataset like FIGER, you query the vector using the mention string only, regardless of the context. 
https://github.com/CogComp/zoe/blob/cf0924b18d144497c440573b7313cfbb4c564fe2/zoe_utils.py#L207
Do you based on the assumption that standard dataset you used don't have two mentions with exactly the same surface form?

**Comment by Slash0BZ** [comment]
Yes, that is a flawed assumption in the experiment, thanks for pointing it out. However, the concatenated mention surfaces rarely overlap in the datasets, as they are named entities and nominals. We re-did the experiments, and the numbers were affected by around 1%.

**Comment by hitercs** [comment]
OK. Got it.

**Comment by Slash0BZ** [comment]
No problem. Please let me know if you have other questions.
