### ISSUE TITLE
Question about sentences number used in learning representation of concept

### ISSUE THREAD

**Issue by hitercs** [CogComp/zoe#24]
Hi,

In your paper, you say "which is the average vector of the representation of **all** the sentences in WIKILINKS that describe the given concept" in Section 3.2.
https://github.com/CogComp/zoe/blob/cf0924b18d144497c440573b7313cfbb4c564fe2/zoe_utils.py#L225
From the code above, do it mean you select **at most 10** sentences in practice to calculate the concept representation?

**Comment by hitercs** [comment]
Ok. But I recommend you clarify this in the paper if you can. Since section 3.2 illustrated representation of **concept** not **type** (The ELMoNN baseline firstly was introduced in section 4.). Thanks.

**Comment by Slash0BZ** [comment]
Thanks, I see your point. We will consider making a clarification.
