### ISSUE TITLE
Question about freebase mapping

### ISSUE THREAD

**Issue by zhaoxy92** [CogComp/zoe#29]
Dear authors, I am trying to customize the mapping from freebase types to my own target taxonomies, however I am having trouble to find a good coverage of all related freebase types. Is there any way or resource that I can use to find out related freebase types for a certain target type? Thank you!

**Comment by Slash0BZ** [comment]
I would suggest looking at a few examples of a specific (new) type and query their FreeBase types. From these results, you might have a clue on how to create the mappings. Note that the mappings support and/or logics, and you can further create your own mapping logics by changing this function: https://github.com/CogComp/zoe/blob/master/zoe_utils.py#L460. You can see that I have a few hacks there to support a broader range of logic mappings.

**Comment by zhaoxy92** [comment]
Will do. Thank you!
