### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by chsuong** [CogComp/zoe#34]
I'm getting the error `AttributeError: module 'tensorflow' has no attribute 'placeholder'` after running the command `python3 main.py bbn.`

`Traceback (most recent call last):
  File "main.py", line 101, in <module>
    runner = ZoeRunner(allow_tensorflow=False)
  File "main.py", line 20, in __init__
    self.elmo_processor = ElmoProcessor(allow_tensorflow)
  File "/scratch/chs298/zoe/zoe_utils.py", line 34, in __init__
    self.batcher, self.ids_placeholder, self.ops, self.sess = initialize_sess(self.vocab_file, self.opt$
  File "/scratch/chs298/zoe/venv/lib/python3.6/site-packages/bilm-0.1-py3.6.egg/bilm/model.py", line 71$
    ids_placeholder = tf.placeholder('int32',
AttributeError: module 'tensorflow' has no attribute 'placeholder'
`

**Comment by Slash0BZ** [comment]
Which version of TensorFlow is this? I am using `1.10.0`. Sorry, I forgot to specify this, and I suspect it's a version issue.

**Comment by chsuong** [comment]
tensorflow==2.0.0. I will try with 1.10.0.
