### ISSUE TITLE
No such file or directory: 'data/log/runlog_figer.pickle'

### ISSUE THREAD

**Issue by chsuong** [CogComp/zoe#35]
After I ran the command "python3 main.py figer," I think the system ran and produced a lot of output on my terminal but spat out an error "No such file or directory: 'data/log/runlog_figer.pickle'".

Below is some of the output:
ELMo Candidate Titles: ['United_States', 'Beltsville,_Maryland', 'United_States_district_court', 'Driving_under_the_influence', 'Kuala_Lumpur', 'Vision_(Marvel_Comics)', 'SM_Entertainment', 'United_Kingdom', 'Jung_Yong_Hwa', 'Super_Junior', 'England_and_Wales', 'IU_(singer)', 'Baden-W%C3%BCrttemberg', 'South_Korea', 'Jabba_the_Hutt', 'Broadcasting_(television_and_radio)', 'Choi_Siwon', 'West_Memphis_3', 'Uthai_Thani_Province', 'Sima_Qian']
Selected Candidate: Federal_Way,_Washington
--Performance--
Strict Accuracy:	0.5916334661354582
--
Micro Precision:	0.7616191904047976
Micro Recall:	0.678237650200267
Micro F1:	0.7175141242937854
--
Macro Precision:	0.7740703851261619
Macro Recall:	0.7231739707835325
Macro F1:	0.7477571070722246

Traceback (most recent call last):
  File "main.py", line 99, in <module>
    runner.save("data/log/runlog_figer.pickle")
  File "main.py", line 80, in save
    with open(file_name, "wb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'data/log/runlog_figer.pickle'

**Comment by Slash0BZ** [comment]
Hi, I think the error is at https://github.com/CogComp/zoe/blob/master/main.py#L99. I should have checked if `./log` exists. I think it's due to a nonexistent path. To solve it, you can either remove line 99 or create `./log`
